version: '3.7'

services:
  export:
    build: ./export
    volumes:
      - data-volume:/var/lib/data
      - ./export/bin:/export
  import:
    build: ./import
    volumes:
      - data-volume:/var/lib/data
      - ./import:/import
    ports:
      - "3000:3000"

volumes:
  data-volume:
