version: '3.7'

services:
  export:
    build: ./export
    volumes:
      - data-volume:/var/lib/data
      - ./export/bin:/export
  import:
    build: ./import
    volumes:
      - data-volume:/var/lib/data
      - ./import:/import
    ports:
      - "3000:3000"
      - "3035:3035"
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

volumes:
  data-volume:
